import { createFileRoute, Link, useNavigate } from '@tanstack/react-router';
import { Eye, EyeOff, ArrowLeft, Loader2 } from 'lucide-react';
import { useState } from 'react';
import { supabase } from '../lib/supabase';
import { ADMIN_EMAIL } from '../lib/servicomoz';

export const Route = createFileRoute('/login')({ component: LoginPage });

function LoginPage() {
  const navigate = useNavigate(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  async function submit(e:React.FormEvent){e.preventDefault();setError('');if(!supabase){setError('Configura o Supabase para entrar.');return;}setLoading(true);const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setError(error.message);setLoading(false);return;}if(email.toLowerCase()===ADMIN_EMAIL){await navigate({to:'/admin'});}else{const {data:p}=await supabase.from('profiles').select('role').eq('id',data.user.id).single();await navigate({to:p?.role==='professional'?'/waiting-room':'/feed'});}setLoading(false);}
  return <main className="flex min-h-screen items-center justify-center bg-[#F8F9FA] px-4"><div className="w-full max-w-md"><Link to="/" className="mb-8 inline-flex items-center gap-2 text-sm text-gray-500"><ArrowLeft size={16}/> Voltar</Link><div className="rounded-2xl border bg-white p-6 shadow-sm sm:p-8"><div className="mb-7"><h1 className="text-2xl font-extrabold">Bem-vindo ao ServiçoMoz</h1><p className="mt-2 text-sm text-gray-500">Entra na tua conta para continuar.</p></div><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium">E-mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required className="mt-1.5 w-full rounded-lg border px-3 py-3 outline-none focus:border-[#00A651]"/></label><label className="block text-sm font-medium">Palavra-passe<div className="relative mt-1.5"><input value={password} onChange={e=>setPassword(e.target.value)} type={show?'text':'password'} required className="w-full rounded-lg border px-3 py-3 pr-11 outline-none focus:border-[#00A651]"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-500">{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-600">{error}</p>}<button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-lg bg-[#00A651] py-3 font-bold text-white disabled:opacity-60">{loading&&<Loader2 className="animate-spin" size={18}/>}Entrar</button></form><button className="mt-4 w-full text-sm font-medium text-[#00A651]">Esqueci a senha</button><p className="mt-6 text-center text-sm text-gray-500">Ainda não tens conta? <Link to="/register" className="font-bold text-[#00A651]">Criar conta</Link></p></div></div></main>;
}
