import { useEffect, useState } from 'react';
import { CheckCircle, ExternalLink, ShieldCheck, XCircle } from 'lucide-react';
import { requireSupabase } from '../../lib/supabase';

export function KycQueue(){
 const supabase=requireSupabase(); const [rows,setRows]=useState<any[]>([]); const [selected,setSelected]=useState<any>(null); const [reason,setReason]=useState(''); const [busy,setBusy]=useState(false);
 const load=async()=>{const {data}=await supabase.from('professional_profiles').select('id,kyc_front_url,kyc_back_url,kyc_selfie_url,kyc_status,profiles!professional_profiles_id_fkey(full_name,email,whatsapp,avatar_url)').eq('kyc_status','pending').order('updated_at',{ascending:true});setRows(data||[])};
 useEffect(()=>{load()},[]);
 const decide=async(ok:boolean)=>{if(!selected||busy)return;if(!ok&&!reason.trim())return;setBusy(true);const update:any=ok?{kyc_status:'approved',verified_badge:true}:{kyc_status:'rejected',kyc_rejection_reason:reason.trim()};const {error}=await supabase.from('professional_profiles').update(update).eq('id',selected.id);if(!error){await supabase.from('notifications').insert({user_id:selected.id,type:ok?'kyc_approved':'kyc_rejected',reference_id:selected.id,body:ok?'O teu badge Verificado ✓ foi activado! O teu perfil agora aparece em destaque.':`A tua verificação foi rejeitada. Motivo: ${reason.trim()}`});setSelected(null);setReason('');await load()}setBusy(false)};
 return <section className="rounded-2xl border bg-white"><header className="flex items-center gap-3 border-b p-4"><ShieldCheck className="text-[#00A651]"/><div><h2 className="text-xl font-bold">KYC — Verificação de identidade</h2><p className="text-sm text-gray-500">{rows.length} verificações pendentes</p></div></header>{rows.length===0?<div className="p-12 text-center text-gray-500">Nenhuma verificação pendente.</div>:<div className="divide-y">{rows.map(r=><div key={r.id} className="flex items-center justify-between gap-4 p-4"><div><p className="font-bold">{r.profiles?.full_name||'Profissional'}</p><p className="text-sm text-gray-500">{r.profiles?.email}</p><p className="text-xs text-gray-400">WhatsApp: {r.profiles?.whatsapp||'—'}</p></div><button onClick={()=>setSelected(r)} className="rounded-lg bg-[#00A651] px-4 py-2 text-sm font-bold text-white">Ver documentos</button></div>)}</div>}{selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-4xl overflow-auto rounded-2xl bg-white p-5"><h3 className="text-lg font-bold">Documentos de {selected.profiles?.full_name}</h3><div className="mt-4 grid gap-4 md:grid-cols-3">{[['BI Frente',selected.kyc_front_url],['BI Verso',selected.kyc_back_url],['Selfie com BI',selected.kyc_selfie_url]].map(([label,path])=><div key={label as string}><p className="mb-2 text-sm font-bold">{label as string}</p><div className="flex h-64 items-center justify-center overflow-hidden rounded-xl border bg-gray-50"><img src={supabase.storage.from('kyc').getPublicUrl(path as string).data.publicUrl} className="max-h-full max-w-full object-contain"/></div><a href={supabase.storage.from('kyc').getPublicUrl(path as string).data.publicUrl} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-xs text-[#00A651]">Abrir imagem <ExternalLink size={13}/></a></div>)}</div><div className="mt-5"><textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={300} placeholder="Motivo da rejeição (obrigatório apenas ao rejeitar)" className="min-h-20 w-full rounded-lg border p-3 text-sm"/></div><div className="mt-4 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button onClick={()=>{setSelected(null);setReason('')}} className="rounded-lg border px-4 py-2 font-semibold">Cancelar</button><button disabled={busy} onClick={()=>decide(false)} className="inline-flex items-center justify-center gap-2 rounded-lg bg-red-500 px-4 py-2 font-bold text-white"><XCircle size={17}/> Rejeitar KYC</button><button disabled={busy} onClick={()=>decide(true)} className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#00A651] px-4 py-2 font-bold text-white"><CheckCircle size={17}/> Aprovar KYC</button></div></div></div>}</section>
}
