import { useState } from 'react';
import { CheckCircle2, Upload, ShieldCheck } from 'lucide-react';
import { requireSupabase } from '../lib/supabase';

export function KycVerification(){
 const supabase=requireSupabase(); const [front,setFront]=useState<File|null>(null); const [back,setBack]=useState<File|null>(null); const [selfie,setSelfie]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState('');
 const upload=async(file:File,userId:string,name:string)=>{const path=`${userId}/kyc/${name}-${Date.now()}.${file.name.split('.').pop()||'jpg'}`;const {error}=await supabase.storage.from('kyc').upload(path,file,{upsert:false});if(error)throw error;return path};
 const submit=async()=>{setError('');if(!front||!back||!selfie){setError('Envia os três documentos para continuar.');return}setBusy(true);try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão expirada.');const [frontUrl,backUrl,selfieUrl]=await Promise.all([upload(front,user.id,'front'),upload(back,user.id,'back'),upload(selfie,user.id,'selfie')]);const {error}=await supabase.from('professional_profiles').update({kyc_front_url:frontUrl,kyc_back_url:backUrl,kyc_selfie_url:selfieUrl,kyc_status:'pending'}).eq('id',user.id);if(error)throw error;setDone(true)}catch(e:any){setError(e?.message||'Não foi possível enviar os documentos.')}finally{setBusy(false)}};
 if(done)return <div className="mx-auto max-w-xl rounded-2xl border bg-white p-8 text-center"><CheckCircle2 className="mx-auto text-[#00A651]" size={52}/><h2 className="mt-4 text-xl font-bold">Documentos enviados</h2><p className="mt-2 text-gray-500">O admin irá verificar os documentos em breve.</p></div>;
 const Field=({label,value,setValue}:{label:string;value:File|null;setValue:(f:File|null)=>void})=><label className="block rounded-xl border-2 border-dashed p-5 text-center cursor-pointer hover:border-[#00A651]"><Upload className="mx-auto text-[#00A651]" size={25}/><span className="mt-2 block text-sm font-semibold">{label}</span><span className="mt-1 block truncate text-xs text-gray-500">{value?.name||'Toque para selecionar uma imagem'}</span><input type="file" accept="image/*" className="hidden" onChange={e=>setValue(e.target.files?.[0]||null)}/></label>;
 return <div className="mx-auto max-w-xl rounded-2xl border bg-white p-5"><div className="flex gap-3 rounded-xl bg-green-50 p-4"><ShieldCheck className="shrink-0 text-[#00A651]"/><div><h2 className="font-bold">Verificação de identidade</h2><p className="text-sm text-gray-600">Envia uma foto nítida do BI frente, BI verso e uma selfie segurando o BI. Estes documentos serão usados apenas para verificação.</p></div></div><div className="mt-5 space-y-3"><Field label="BI Frente" value={front} setValue={setFront}/><Field label="BI Verso" value={back} setValue={setBack}/><Field label="Selfie segurando o BI" value={selfie} setValue={setSelfie}/></div>{error&&<p className="mt-3 text-sm font-medium text-red-500">{error}</p>}<button onClick={submit} disabled={busy} className="mt-5 w-full rounded-lg bg-[#00A651] py-3 font-bold text-white disabled:opacity-50">{busy?'A enviar...':'Enviar documentos'}</button></div>
}
