import { useEffect, useState } from 'react';
import { MessageCircle, Send, Search } from 'lucide-react';
import { requireSupabase } from '../lib/supabase';

export function Messaging({conversationId}:{conversationId?:string}){const supabase=requireSupabase();const [user,setUser]=useState<any>(null);const [conversations,setConversations]=useState<any[]>([]);const [messages,setMessages]=useState<any[]>([]);const [active,setActive]=useState(conversationId||'');const [text,setText]=useState('');const [search,setSearch]=useState('');
useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();setUser(user);if(!user)return;const {data}=await supabase.from('conversations').select('*').or(`participant_a.eq.${user.id},participant_b.eq.${user.id}`).order('last_message_at',{ascending:false});setConversations(data||[])})()},[supabase]);
useEffect(()=>{if(!active)return;let channel:any;(async()=>{const {data}=await supabase.from('messages').select('*').eq('conversation_id',active).order('created_at');setMessages(data||[]);channel=supabase.channel(`messages-${active}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${active}`},payload=>setMessages(v=>[...v,payload.new])).subscribe();await supabase.from('messages').update({read:true}).eq('conversation_id',active).neq('sender_id',user?.id)})();return()=>{if(channel)supabase.removeChannel(channel)}}},[active,user?.id,supabase]);
const send=async()=>{if(!text.trim()||!user||!active)return;const content=text.trim();setText('');await supabase.from('messages').insert({conversation_id:active,sender_id:user.id,content});await supabase.from('conversations').update({last_message:content,last_message_at:new Date().toISOString()}).eq('id',active)};
const filtered=conversations.filter(c=>JSON.stringify(c).toLowerCase().includes(search.toLowerCase()));return <div className="flex min-h-[70vh] overflow-hidden rounded-2xl border bg-white"><aside className="w-full max-w-xs border-r"><div className="p-3"><div className="flex items-center gap-2 rounded-lg border px-3"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar conversas" className="w-full py-2 text-sm outline-none"/></div></div>{filtered.map(c=><button key={c.id} onClick={()=>setActive(c.id)} className={`w-full border-t p-4 text-left ${active===c.id?'bg-green-50':''}`}><div className="flex gap-3"><div className="grid size-10 place-items-center rounded-full bg-gray-100"><MessageCircle size={18}/></div><div className="min-w-0"><div className="truncate text-sm font-bold">Conversa</div><div className="truncate text-xs text-gray-500">{c.last_message||'Nova conversa'}</div></div></div></button>)}</aside><main className="hidden flex-1 flex-col md:flex">{active?<><div className="border-b p-4 font-bold">Mensagens</div><div className="flex-1 space-y-2 overflow-y-auto p-4">{messages.map(m=><div key={m.id} className={`flex ${m.sender_id===user?.id?'justify-end':''}`}><div className={`max-w-[75%] rounded-2xl px-4 py-2 text-sm ${m.sender_id===user?.id?'bg-[#00A651] text-white':'bg-gray-100'}`}>{m.content}</div></div>)}</div><div className="flex gap-2 border-t p-3"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Escreve uma mensagem..." className="flex-1 rounded-xl border px-4 py-3 text-sm outline-none"/><button onClick={send} className="grid size-11 place-items-center rounded-xl bg-[#00A651] text-white"><Send size={18}/></button></div></>:<div className="m-auto text-center text-gray-400"><MessageCircle className="mx-auto" size={44}/><p className="mt-2">Seleciona uma conversa</p></div>}</main></div>}
