import { useEffect, useState } from 'react';
import { Bell, Check } from 'lucide-react';
import { requireSupabase } from '../lib/supabase';

export function Notifications(){
 const supabase=requireSupabase(); const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{let channel:any;let mounted=true;(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const {data}=await supabase.from('notifications').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100);if(mounted)setItems(data||[]);channel=supabase.channel(`notifications-${user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`user_id=eq.${user.id}`},payload=>setItems(v=>[payload.new,...v])).subscribe();setLoading(false)})();return()=>{mounted=false;if(channel)supabase.removeChannel(channel)}},[supabase]);
 const unread=items.filter(n=>!n.read).length; const markAll=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.from('notifications').update({read:true}).eq('user_id',user.id).eq('read',false);setItems(v=>v.map(n=>({...n,read:true})))}; const mark=async(id:string)=>{await supabase.from('notifications').update({read:true}).eq('id',id);setItems(v=>v.map(n=>n.id===id?{...n,read:true}:n))};
 return <section className="mx-auto w-full max-w-2xl rounded-2xl border bg-white"><header className="flex items-center justify-between border-b p-4"><div><h1 className="text-xl font-bold">Notificações</h1><p className="text-sm text-gray-500">{unread} não lidas</p></div><button disabled={!unread} onClick={markAll} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm font-semibold disabled:opacity-40"><Check size={16}/> Marcar todas como lidas</button></header>{loading?<div className="space-y-3 p-4"><div className="h-16 animate-pulse rounded-xl bg-gray-100"/><div className="h-16 animate-pulse rounded-xl bg-gray-100"/></div>:items.length===0?<div className="p-12 text-center text-gray-400"><Bell className="mx-auto" size={42}/><p className="mt-3 font-medium">Ainda não tens notificações.</p></div>:<div>{items.map(n=><button key={n.id} onClick={()=>mark(n.id)} className={`flex w-full gap-3 border-b p-4 text-left last:border-0 ${n.read?'bg-white':'bg-green-50'}`}><div className="grid size-10 shrink-0 place-items-center rounded-full bg-green-100 text-[#00A651]"><Bell size={18}/></div><div className="min-w-0 flex-1"><p className="text-sm text-gray-800">{n.body||'Tens uma nova notificação.'}</p><p className="mt-1 text-xs text-gray-400">{new Date(n.created_at).toLocaleString('pt-MZ')}</p></div>{!n.read&&<span className="mt-2 size-2 shrink-0 rounded-full bg-red-500"/>}</button>)}</div>}</section>
}
