import { useEffect, useState } from 'react';
import { Bookmark, Heart, MessageCircle } from 'lucide-react';
import { requireSupabase } from '../lib/supabase';

export function PostInteractions({postId, initialLikes=0, initialComments=0}:{postId:string;initialLikes?:number;initialComments?:number}){
 const supabase=requireSupabase(); const [liked,setLiked]=useState(false); const [saved,setSaved]=useState(false); const [likes,setLikes]=useState(initialLikes); const [comment,setComment]=useState(''); const [comments,setComments]=useState<any[]>([]); const [open,setOpen]=useState(false); const [sending,setSending]=useState(false);
 useEffect(()=>{let mounted=true;(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [l,s,c]=await Promise.all([supabase.from('post_likes').select('id').eq('post_id',postId).eq('user_id',user.id).maybeSingle(),supabase.from('post_saves').select('id').eq('post_id',postId).eq('user_id',user.id).maybeSingle(),supabase.from('post_comments').select('id,content,created_at,user_id').eq('post_id',postId).order('created_at',{ascending:true})]);if(mounted){setLiked(!!l.data);setSaved(!!s.data);setComments(c.data??[]);}})();return()=>{mounted=false}},[postId,supabase]);
 const toggleLike=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;if(liked){await supabase.from('post_likes').delete().eq('post_id',postId).eq('user_id',user.id);setLiked(false);setLikes(v=>Math.max(0,v-1));}else{await supabase.from('post_likes').insert({post_id:postId,user_id:user.id});setLiked(true);setLikes(v=>v+1);}};
 const toggleSave=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;if(saved){await supabase.from('post_saves').delete().eq('post_id',postId).eq('user_id',user.id);setSaved(false)}else{await supabase.from('post_saves').insert({post_id:postId,user_id:user.id});setSaved(true)}};
 const send=async()=>{if(!comment.trim()||sending)return;setSending(true);const {data:{user}}=await supabase.auth.getUser();if(user){const {data}=await supabase.from('post_comments').insert({post_id:postId,user_id:user.id,content:comment.trim()}).select().single();if(data){setComments(v=>[...v,data]);setComment('')}}setSending(false)};
 return <div className="border-t px-4 py-3"><div className="flex items-center gap-5"><button onClick={toggleLike} className={liked?'text-red-500':'text-gray-600'}><Heart size={22} fill={liked?'currentColor':'none'}/><span className="ml-1 text-xs">{likes}</span></button><button onClick={()=>setOpen(v=>!v)} className="text-gray-600"><MessageCircle size={22}/><span className="ml-1 text-xs">{comments.length||initialComments}</span></button><button onClick={toggleSave} className="ml-auto text-gray-600"><Bookmark size={22} fill={saved?'currentColor':'none'}/></button></div>{open&&<div className="mt-3"><div className="max-h-40 space-y-2 overflow-y-auto">{comments.map(c=><div key={c.id} className="rounded-lg bg-gray-50 p-2 text-sm">{c.content}</div>)}</div><div className="mt-2 flex gap-2"><input value={comment} onChange={e=>setComment(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} maxLength={300} placeholder="Escreve um comentário..." className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-sm outline-none"/><button onClick={send} disabled={sending||!comment.trim()} className="rounded-lg bg-[#00A651] px-3 py-2 text-sm font-bold text-white disabled:opacity-50">Enviar</button></div></div>}</div>;
}
